/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_reservation_system_gui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Yossan
 */
public class MainForm extends javax.swing.JFrame {
    private int receptionistId;
    private boolean isAdmin;
    /**
     * Creates new form MainForm
     */
    public MainForm(String username, boolean isAdmin) {
        initComponents();
        this.isAdmin = isAdmin;
        if(isAdmin) {
             jLabelWelcome.setText("Welcome, " + username);
             receptionistId = -1;
        } else {
            String name = "Guest";
            String receptionistPhone = username;
            MyConnection conn = new MyConnection();
            PreparedStatement ps;
            ResultSet rst;
            String sql = "SELECT * FROM Receptionist WHERE phone = ?";

            try {
                ps = conn.createConnection().prepareStatement(sql);
                ps.setString(1, username);
                rst = ps.executeQuery();
                rst.next();
                name = rst.getString("name");
                receptionistId = rst.getInt("id");
            } catch(SQLException e) {
                System.out.println(e);
            }

            jLabelWelcome.setText("Welcome, " + name);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMenu = new javax.swing.JMenu();
        jMenuItemReservation = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemReceptioist = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRoom = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCustomer = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabelWelcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelWelcome.setText("Welcome , Guest!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabelWelcome)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabelWelcome)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        jMenuMenu.setText("Menu >");
        jMenuMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMenuActionPerformed(evt);
            }
        });

        jMenuItemReservation.setText("Reservation");
        jMenuItemReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservationActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemReservation);
        jMenuMenu.add(jSeparator1);

        jMenuItemReceptioist.setText("Receptionist");
        jMenuItemReceptioist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReceptioistActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemReceptioist);
        jMenuMenu.add(jSeparator2);

        jMenuItemRoom.setText("Room");
        jMenuItemRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRoomActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemRoom);
        jMenuMenu.add(jSeparator3);

        jMenuItemCustomer.setText("Customer");
        jMenuItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemCustomer);
        jMenuMenu.add(jSeparator4);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemLogout);

        jMenuBar1.add(jMenuMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservationActionPerformed
        if(isAdmin) {
            JOptionPane.showMessageDialog(rootPane, "You Are Not an Receptionist", "Receptionist Required", JOptionPane.ERROR_MESSAGE);
        } else {
            MenuReservationForm reservationForm = new MenuReservationForm(receptionistId);
            reservationForm.setVisible(true);
            reservationForm.pack();
            reservationForm.setLocationRelativeTo(null);
            reservationForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
        
    }//GEN-LAST:event_jMenuItemReservationActionPerformed

    private void jMenuItemReceptioistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReceptioistActionPerformed
        if(isAdmin) {
            MenuReceptionistForm receptionistForm = new MenuReceptionistForm();
            receptionistForm.setVisible(true);
            receptionistForm.pack();
            receptionistForm.setLocationRelativeTo(null);
            receptionistForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "You Are Not an Admin", "Admin Required", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItemReceptioistActionPerformed

    private void jMenuItemRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRoomActionPerformed
        if(isAdmin) {
            MenuRoomForm roomForm = new MenuRoomForm();
            roomForm.setVisible(true);
            roomForm.pack();
            roomForm.setLocationRelativeTo(null);
            roomForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "You Are Not an Admin", "Admin Required", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jMenuItemRoomActionPerformed

    private void jMenuItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerActionPerformed
        if(isAdmin) {
            JOptionPane.showMessageDialog(rootPane, "You Are Not an Receptionist", "Receptionist Required", JOptionPane.ERROR_MESSAGE);
        } else {
            MenuCustomerForm customerForm = new MenuCustomerForm();
            customerForm.setVisible(true);
            customerForm.pack();
            customerForm.setLocationRelativeTo(null);
            customerForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_jMenuItemCustomerActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMenuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCustomer;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemReceptioist;
    private javax.swing.JMenuItem jMenuItemReservation;
    private javax.swing.JMenuItem jMenuItemRoom;
    private javax.swing.JMenu jMenuMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
